builders:
  state_store:
    import: "package:state_gen/builder.dart"
    builder_factories: ["stateBuilder"]
    build_extensions: {"dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]